/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _WHO_H_RPCGEN
#define _WHO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define WHO_PROG 0x31423467
#define WHO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define STR_WHO 1
extern  char ** str_who_1(void *, CLIENT *);
extern  char ** str_who_1_svc(void *, struct svc_req *);
extern int who_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define STR_WHO 1
extern  char ** str_who_1();
extern  char ** str_who_1_svc();
extern int who_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_WHO_H_RPCGEN */
