/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "who.h"
#include <utmp.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>

char **
str_who_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

    struct utmp *curr_record;
    curr_record = getutent();

    while(curr_record != NULL) {
        strncpy(result, curr_record->ut_user,32);
        curr_record = getutent();
    }
	return &result;
}
